/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'turquoise': {
          DEFAULT: '#40E0D0',
          '50': '#E6FBFA',
          '100': '#C5F5F2',
          '200': '#94ECE6',
          '300': '#63E3DA',
          '400': '#40E0D0',
          '500': '#25C9B9',
          '600': '#1D9E91',
          '700': '#167369',
          '800': '#0F4941',
          '900': '#071F1C',
        },
        'teal': {
          DEFAULT: '#008080',
          '50': '#E6FFFF',
          '100': '#B3FFFF',
          '200': '#66FFFF',
          '300': '#19FFFF',
          '400': '#00CCCC',
          '500': '#008080',
          '600': '#006666',
          '700': '#004D4D',
          '800': '#003333',
          '900': '#001A1A',
        },
        primary: {
          50: '#E6F6F6',
          100: '#B2E8E8',
          200: '#7FDADA',
          300: '#4ACCCC',
          400: '#26B5B5',
          500: '#14898A',
          600: '#0F6A6B',
          700: '#0A4B4C',
        },
        accent: '#62B299',
        coral: '#FF6B6B',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'dm-sans': ['DM Sans', 'sans-serif'],
      },
      animation: {
        'pulse': 'pulse 6s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-slow': 'pulse 8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-slower': 'pulse 10s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-medium': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float1': 'float1 10s ease-in-out infinite',
        'float2': 'float2 13s ease-in-out infinite',
        'float3': 'float3 15s ease-in-out infinite',
        'float-slow': 'float-slow 20s ease-in-out infinite',
        'float-reverse': 'float-reverse 18s ease-in-out infinite',
        'rotate-slow': 'rotate 30s linear infinite',
        'wave1': 'wave1 15s ease-in-out infinite',
        'wave2': 'wave2 18s ease-in-out infinite',
        'flow': 'flow 20s linear infinite',
        'diagonal-slow': 'diagonal 30s linear infinite',
        'float-slow': 'float 15s ease-in-out infinite',
        'float-medium': 'float 10s ease-in-out infinite',
        'float-fast': 'float 7s ease-in-out infinite',
        'float-delay': 'float 12s ease-in-out infinite 2s',
        'float-delay-2': 'float 14s ease-in-out infinite 4s',
        'fade': 'fadeInOut 6s ease-in-out infinite',
        'fade-delay': 'fadeInOut 6s ease-in-out infinite 3s',
        'fade-delay-2': 'fadeInOut 6s ease-in-out infinite 6s',
        'bounce-slow': 'bounce 3s infinite',
        'slight-bounce': 'slightBounce 2s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s infinite',
        'shine': 'shine 1.5s forwards',
      },
      keyframes: {
        pulse: {
          '0%, 100%': { opacity: 0.2 },
          '50%': { opacity: 0.4 },
        },
        float1: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-10px) translateX(10px)' },
          '50%': { transform: 'translateY(0) translateX(20px)' },
          '75%': { transform: 'translateY(10px) translateX(10px)' },
        },
        float2: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(12px) translateX(-12px)' },
          '50%': { transform: 'translateY(0) translateX(-24px)' },
          '75%': { transform: 'translateY(-12px) translateX(-12px)' },
        },
        float3: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-15px) translateX(-15px)' },
          '50%': { transform: 'translateY(0) translateX(-30px)' },
          '75%': { transform: 'translateY(15px) translateX(-15px)' },
        },
        'float-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'float-reverse': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(20px)' },
        },
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        wave1: {
          '0%, 100%': { transform: 'translateX(0%)' },
          '50%': { transform: 'translateX(-25%)' },
        },
        wave2: {
          '0%, 100%': { transform: 'translateX(0%)' },
          '50%': { transform: 'translateX(25%)' },
        },
        flow: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-100%)' },
        },
        diagonal: {
          '0%': { transform: 'translateX(0) translateY(0)' },
          '100%': { transform: 'translateX(-100%) translateY(-100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        fadeInOut: {
          '0%, 100%': { opacity: '0' },
          '25%, 75%': { opacity: '1' },
        },
        slightBounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-3px)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        shine: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
}
